version: '3.8'

networks:
  elastic:    # name: host

services:
  elasticsearch:
    labels:
      filebeat: true
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    hostname: elasticsearch
    container_name: elasticsearch-prevail
    networks: 
      - elastic
    ports: 
      - '14997:9200'
      - '14998:9300'
    environment:
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=basic
      - network.host=0.0.0.0 
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
      - esdata:/usr/share/elasticsearch/data   
    healthcheck:
      test: curl -u elastic:pass1234 -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    labels:
      filebeat: false
    image: docker.elastic.co/kibana/kibana:8.7.0
    hostname: kibana
    container_name: kibana-prevail
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]'
      - "SERVER_NAME=localhost"
      - "XPACK_MONITORING_ENABLED=false"
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
      - discovery.type=single-node
    networks: 
      - elastic
    ports: 
      - '14999:5602'
    # configs:
    #   - source: ki_config
    #     target: /usr/share/kibana/config/kibana.yml
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: always
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    healthcheck:
      test: curl -s -I http://localhost:5602 | grep -q 'HTTP/1.1 302 Found'
      interval: 10s
      timeout: 10s
      retries: 120

  logstash:
    labels:
      filebeat: true
    image: docker.elastic.co/logstash/logstash:8.7.0
    hostname: logstash
    container_name: logstash-prevail
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_URL=http://elasticsearch:9200
      - discovery.type=single-node
    networks: 
      - elastic
    ports: 
        - '15000:5044'
        - '15001:5000'
        - '15002:5001'
        - '15003:9600'
    # configs:
    #     - source: ls_config
    #       target: /usr/share/logstash/pipeline/logstash.conf
    volumes:
      - ./config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
        elasticsearch:
          condition: service_healthy
    restart: always
    healthcheck:
      test: curl -XGET 'localhost:9600/?pretty'
      interval: 10s
      timeout: 10s
      retries: 120

  elasticsearch-mapping-init:
    build: elasticsearch-mapping-init
    container_name: elasticsearch-mapping-init
    networks: 
      - elastic
    links:
      - elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
